#! /bin/sh
#
# Attempt to boot the autoconf system, making the configure
# script and makefile input template.
#
# License inherited from enclosing/including source package.
#

PROG=${0##*/}

# auto* tools might demand version be specified in environment
# if multiple versions are installed
# autoconf and automake --version will succeed, or fail; in the
# latter case try forcing versions (and if they are wrong, then
# let the user figure it out)
autoconf --version >/dev/null 2>&1 || {
    : ${AUTOCONF_VERSION:=2.69}
    export AUTOCONF_VERSION
}

automake --version >/dev/null 2>&1 || {
    : ${AUTOMAKE_VERSION:=1.11}
    export AUTOMAKE_VERSION
}

: ${ALLDIRS:="."}

e2 () { printf '%s: %s\n' "$PROG" "$*" 1>&2; }
fail () { e2 "$@"; exit 1; }

AREC='autoreconf -fiv --no-recursive'

splay () {
    ( cd "$1" && $AREC ) || \
        fail failed \"$AREC\" in \""$1"\"
}

rm -rf autom4te.cache

for D in $ALLDIRS ; do
    e2 running \"$AREC\" in \""$D"\"
    splay "$D"
done

